services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskmanager"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:123456@postgres:5432/taskmanager?schema=public"
      PORT: "4000"
    ports:
      - "4001:4000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data: